- task-representation.md
Here's an initial attempt at how we could represent tasks. We can make adjustments to this as we try it out, and I can build it into a web form once we decide we like it.
> Initial attempt at task representation

- tasks/public_goods_task.md
https://github.com/Watts-Lab/task-mapping/issues/56
> Public goods task

- reproducing arts.md
https://github.com/Watts-Lab/task-mapping/issues/60
> Reproducing arts

- tasks/Public goods task.md
> Cleaned up some lines

- Sender-receiver-game.md
- tasks/{sender-receiver game}.md
https://github.com/Watts-Lab/task-mapping/issues/28
> sender-receiver game

- Group typing.md
https://github.com/Watts-Lab/task-mapping/issues/71
> Group typing

- Logic Problem.md
https://github.com/Watts-Lab/task-mapping/issues/95
> Create Logic Problem.md

- Hidden figure in a picture.md
https://github.com/Watts-Lab/task-mapping/issues/129
> Hidden figures in a picture

- tasks/Summarize Discussion.md
Wrote instructions since none exist- I did use prompts that were referenced in other Hackman papers
> Update Summarize Discussion.md

- tasks/Search for Oil Task.md
I developed some instructions based on existing "search" tasks in this paper (pg 135): https://files.eric.ed.gov/fulltext/ED030955.pdf
I hope that's alright!
> Update Search for Oil Task.md

- tasks/Ultimatum game (various versions).md
> Update Ultimatum game (various versions).md

- tasks/Word completion given starting letter.md
https://github.com/Watts-Lab/task-mapping/issues/226
> Word completion given starting letter

- tasks/Bullard Houses.md
https://github.com/Watts-Lab/task-mapping/issues/206
> Create Bullard Houses.md

- tasks/Estimating social quantity.md
> Update Estimating social quantity.md

- tasks/Manipulation (change object to goal state).md
https://github.com/Watts-Lab/task-mapping/issues/245
> Manipulation (change object to goal state)

- Run a mini business.md
https://github.com/Watts-Lab/task-mapping/issues/241
> Create Run a mini business.md

- tasks/Hidden figure in a picture.md
I wrote in instructions but there are other tasks embedded in this- how do you want to address instructions for the 'distractor'  tasks @markwhiting 
Also- the stimuli are from a book I added the Amazon link to purchase it
> Update Hidden figure in a picture.md

- tasks/Divergent Association Task.md
> Update Divergent Association Task.md

- Wason’s Selection Task.md
https://github.com/Watts-Lab/task-mapping/issues/286
> Wason’s selection task

- tasks/Apache-helicopter-flight-simulator.md
Just creating the pull request to allow for easier tracking
> Apache helicopter flight simulator

- tasks/Computer maze.md
> Computer maze

- tasks/Moving offices (complex task).md
> Moving offices (complex task)

- Candle task.md
> Candle task

- tasks/Mathematical puzzle 1.md
> Mathematical puzzle 1

- tasks/Mathematical puzzle 3.md
> Mathematical puzzle 3

- tasks/Mathematical puzzle 4.md
> Mathematical puzzle 4
